$(document).ready(function(){
	$("#register").hide();
	$("#first").click(function(){
		$("#register").hide();
		$("#login").show();
	});
	$("#second").click(function(){
		$("#login").hide();
		$("#register").show();
	});
});